name:                wasm-experiment1
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md

dependencies:
- base >= 4.8 && < 5
- bytestring
- text
- text-builder
- vector

library:
  source-dirs: src
  ghc-options: -pgml gcc "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lwasmtime" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"

executables:
  wasm-experiment1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-experiment1

tests:
  wasm-experiment1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-experiment1
    - hspec
    - directory
    - filepath
