name:                wasm-experiment1
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md

dependencies:
- base >= 4.8 && < 5
- bytestring
- containers
- filepath
- megaparsec
- text
- vector
- vector-builder

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs

library:
  source-dirs: src
  ld-options:
  - -Wl,--whole-archive
  - -Wl,-Bstatic
  - -Wl,-lwasmtime
  - -Wl,-Bdynamic
  - -Wl,--no-whole-archive

executables:
  compiler:
    main:                Main.hs
    source-dirs:         compiler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-experiment1
  wasmtime-example:
    main:                Main.hs
    source-dirs:         wasmtime-example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-experiment1

tests:
  wasm-experiment1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wasm-experiment1
    - hspec
    - directory
    - filepath

  native-test:
    main:                Main.hs
    source-dirs:         native-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process
    - wasm-experiment1
